### ISSUE TITLE
private-key.h not found in your package 

### ISSUE THREAD

**Issue by mv2050arshad** [plstcharles/meta-licensor#3]
Hi

thanks in advance for your nice library. but i still have many problem in front of it.
not found this file that mentioned in code, so i can not compile and using it.

thanks in advance

**Comment by plstcharles** [comment]
Hello;
The private key should be generated on your computer as you build the library. If you run cmake in `<project_dir>/build`, the header file for the key will then be located at `<project_dir>/build/keys/metalicensor/keys/private-key.h`. Note that this file should remain private (it's like a server key), thus why it is not distributed with the repository.

**Comment by mv2050arshad** [comment]
thanks
